xoofx/markdig

src/Markdig.Tests/Markdig.Tests.csproj
src/Markdig.Tests/TestLinkHelper.cs
src/Markdig.Tests/project.json
src/Markdig/Helpers/LinkHelper.cs

Feel free to ignore changes to project.json and the .csproj - those are solely for allowing me to utilize the VS Test Runner:
Added dependency in project.json: NUnit3TestAdapter
Disabled "Prefer 32-bit" on Markdig.Tests(.csproj) to accommodate NUnit.

Include digits after first letter in Urilize (for Auto-Identifiers)

---

src/Markdig/Extensions/NoRefLinks/NoFollowLinksExtension.cs
src/Markdig/Extensions/NoRefLinks/NoRefLinksExtension.cs
src/Markdig/MarkdownExtensions.cs
src/Markdig/Renderers/Html/Inlines/AutolinkInlineRenderer.cs
src/Markdig/Renderers/Html/Inlines/LinkInlineRenderer.cs

This PR adds support for automatically adding rel=nofollow to HTML links - this in many times is desired (if not necessary) especially when allowing content that is not necessarily trusted to be published.

Adding support for rel=nofollow in links

---

src/Markdig/Parsers/Inlines/EmphasisInlineParser.cs

Scenario:
```
***Strong emphasis*** normal
```
Should result in:
```
<p><strong><em>Strong emphasis</em></strong> normal</p>
```
But actually outputs:
```
<p><strong><em>Strong emphasis</em> normal</strong></p>
```
**Note:** I haven't included a spec to demonstrate the fix, as the specs for this part comes from CommonMark. Would you prefer me to add a new spec to this pull request, or to submit a pull request to the CommonMark spec?

Fixes issue where sentences containing strong emphasis words did not correctly delimit the strong tag

---

src/Markdig.Tests/Specs/MathSpecs.md
src/Markdig.Tests/Specs/Specs.cs
src/Markdig/Extensions/Mathematics/MathInlineParser.cs

I found an issue where inline math with trailing text both included the text _inside_ the maths block and _outside_ the maths block.
For example:
```
This is a $math block$ with text on both sides.
````
Should render as
```html
<p>This is a <span class="math">math block</span> with text on both sides.</p>
```
But instead we get
```html
<p>This is a <span class="math">math block$ with text on both sides.</span> with text on both sides.</p>
```

Fixes issue where trailing text after an inline math block is both included in the math block and appended after the math block.

---

src/Markdig.Tests/Specs/ListExtraSpecs.md
src/Markdig.Tests/Specs/Specs.cs
src/Markdig/Extensions/ListExtras/ListExtraItemParser.cs
src/Markdig/Helpers/CharHelper.cs
src/Markdig/Renderers/Html/ListRenderer.cs

The List Extra extension currently outputs whatever the next value is when continuing lists, which may not be a valid integer.
I've changed it so it converts latin and roman characters to the appropriate number for the start attribute.

Changes List Extra to output valid integer for start attribute, instead of roman or latin character.

---

src/Markdig.Tests/Specs/DefinitionListSpecs.md
src/Markdig.Tests/Specs/Specs.cs
src/Markdig/Extensions/DefinitionLists/DefinitionListParser.cs

I've experienced an issue where a nested definition list outputs multiple definition lists, instead of one list with multiple terms.
The following markdown:
```md
1.  Item One
2.  Item Two
Term One
:   Description One
Term Two
:   Description Two
Term Three
:   Description Three
3.  Item Three
```
is rendered as:
```html
<ol>
<li><p>Item One</p></li>
<li><p>Item Two</p>
<dl>
<dt>Term One</dt>
<dd>Description One</dd>
</dl>
<dl>
<dt>Term Two</dt>
<dd>Description Two</dd>
</dl>
<dl>
<dt>Term Three</dt>
<dd>Description Three</dd>
</dl>
</li>
<li><p>Item Three</p></li>
</ol>
```
instead of:
```html
<ol>
<li><p>Item One</p></li>
<li><p>Item Two</p>
<dl>
<dt>Term One</dt>
<dd>Description One</dd>
<dt>Term Two</dt>
<dd>Description Two</dd>
<dt>Term Three</dt>
<dd>Description Three</dd>
</dl> …
```

Fixes issue where multiple definition lists are created when they are nested in a list item.

---

src/Markdig.Tests/Specs/ListExtraSpecs.md
src/Markdig.Tests/Specs/Specs.cs
src/Markdig/Parsers/BlockProcessor.cs
src/Markdig/Parsers/ListBlockParser.cs

This fixes #54.
Due to the way `IBlock.IsOpen` is used, it wasn't possible to just check that property, so I have added an internal method to `BlockProcesser` to check if the block is still contained in the `OpenedBlocks` collection.

Checks if paragraph block is closed when deciding if continuation list is allowable with character other than '1.'

---

src/Markdig.Tests/Specs/AbbreviationSpecs.md
src/Markdig.Tests/Specs/Specs.cs
src/Markdig/Helpers/TextMatcher.cs

When you have multiple, similar (when an abbreviation is a substring of another abbreviation) abbreviations then only the first abbreviation will be applied.
For example:
```md
*[1A]: First
*[1A1]: Second
*[1A2]: Third
We can abbreviate 1A, 1A1 and 1A2!
```
should result in:
```html
<p>We can abbreviate <abbr title="First">1A</abbr>, <abbr title="Second">1A1</abbr> and <abbr title="Third">1A2</abbr>!</p>
```
but instead we get:
```html
<p>We can abbreviate <abbr title="First">1A</abbr>, 1A1 and 1A2!</p>
```

Fixes problem with multiple, similar abbreviations not parsing correctly

---

src/Markdig.Tests/Specs/EmphasisExtraSpecs.md
src/Markdig.Tests/Specs/Specs.cs
src/Markdig/Helpers/CharHelper.cs

I'm not sure how you'll feel about this one.
The CommonMark spec identifies when whitespace and punctuation can be used as left- and right-flanking delimiter runs. This logic is also used for the extra emphasis extension.
There are cases where certain puntuation characters _should_(?) be allowed.
For example, the minus symbol (or it's more commonly used lookalike, the dash) ought to be allowed as the start of a superscript span:
>
```md
One quintillionth can be expressed as 10^-18^
```
```html
<p>One quintillionth can be expressed as 10<sup>-18</sup></p>
```
><p>One quintillionth can be expressed as 10<sup>-18</sup></p>
Similarly the dagger and double-dagger are commonly used as localised note markers (followed by §, || and #) so should be allowed as the sole contents of a superscript …

Adds exceptions to allow certain punctuation characters to behave as inline delimiters

---

src/Markdig.Tests/Specs/GridTableSpecs.md
src/Markdig.Tests/Specs/Specs.cs
src/Markdig/Extensions/Tables/GridTableParser.cs
src/Markdig/Extensions/Tables/HtmlTableRenderer.cs
src/Markdig/Extensions/Tables/Table.cs
src/Markdig/Extensions/Tables/TableCell.cs

I'm afraid I changed the `Grid Table Parser` quite a bit here.
Feel free to wrap my knuckles and suggest better changes though!
This adds support for cells spanning rows, in addition to columns.

Adds support for rowspans in grid tables

---

src/Markdig/Extensions/Abbreviations/AbbreviationParser.cs
src/Markdig/Parsers/InlineProcessor.cs

I discovered a very strange issue when using abbreviations inline after a _potential_ delimiter (in my case, a colon).
The code would throw an `ArgumentException` from line 54 of `ContainerInline.cs`.
Example:
```md
Some abbreviations: HTML, WWW
*[HTML]: Hypertext Markup Language
*[WWW]: World Wide Web
```
This is due to the processor storing the first part of the content in a `LiteralInline` while it tries to validate the character as a valid delimiter. When this fails it returns and continues with the rest of the inline, including the first section. This means that when the `AbbreviationParser` finds a valid abbreviation during the post match, the `LiteralInline` already has a parent, which throws the exception.
The solution involves using the existing `LiteralInline` parent as the …

Fixes issue when using colon (among others) on lines with abbreviations

---

src/Markdig.Tests/Specs/AbbreviationSpecs.md
src/Markdig.Tests/Specs/Specs.cs
src/Markdig/Extensions/Abbreviations/AbbreviationParser.cs

I've had an issue where abbreviations are being created for words that contain punctuation.
Example:
```md
*[1A]: First
We should not abbreviate 1.1A
```
Is rendered as:
```html
<p>We should not abbreviate 1.<abbr title="First">1A</abbr></p>
```
I've adjusted the `AbbreviationParser` to allow punctuation to embrace matches only if they are further embraced by \0 or whitespace.

Fixes issue where punctuation forms part of word, so abbreviation is not valid

---

src/Markdig/Parsers/Inlines/LiteralInlineParser.cs

I've found an odd situation where the `AbbreviationParser` throws a cast exception when `processor.Inline` is not of type `LiteralInline`. See lines 69-90 of `LiteralInlineParser`. In my case the type was `EmphasisDelimiterInline` and the current `StringSlice` was empty.
There are 2 ways I could have gone about this. I have chosen to _assume_ that it is valid to expect the `LiteralInlineParser` to only call the `PostMatch` event when the `processor.Inline` type is `LiteralInline` so have changed the event raising code accordingly.
The alternative is that the consuming code should not make assumptions about the type of inline that the processor is handling and should handle it accordingly. Let me know if you'd rather I went down this route.

Fixes issue where LiteralInlineParser calls PostMatch while processor.Inline is type other than LiteralInline

---

src/Markdig/Extensions/ListExtras/ListExtraItemParser.cs
src/Markdig/Helpers/CharHelper.cs

Due to use of Char.ToUpper, ListExtraItemParser fails in cultures like Turkish where uppercase of 'i' is 'İ'. Char.ToUpperInvariant should be used instead.

Use Char.ToUpperInvariant instead of Char.ToUpper

---

src/Markdig.Tests/Specs/AbbreviationSpecs.md
src/Markdig.Tests/Specs/Specs.cs
src/Markdig/Extensions/Abbreviations/AbbreviationParser.cs

I made a schoolboy error in my previous fix for the abbreviation parser.
It works perfectly well for _most_ cases, but has issues where an _almost_ valid abbreviation is the first, last or only value in the correct content block.

Fixes the IsValidAbbreviation method in AbbreviationParser

---

src/Markdig.Tests/TestLinkHelper.cs
src/Markdig/Helpers/ICharIterator.cs
src/Markdig/Helpers/LinkHelper.cs
src/Markdig/Helpers/StringLineGroup.cs
src/Markdig/Helpers/StringSlice.cs

A bare URL in a markdown file is interpreted as a URL and rendered accordingly in HTML. However, if the URL is followed by a full stop (.) that full stop is interpreted as being part of the URL. For example consider the URL www.google.com. Because there was a full stop immediately after the URL, Markdig would render this in HTML as `<a href="www.google.com.">www.google.com.</a>`.
This behaviour does not seem terribly unreasonable, given that the trailing dot may constitute a valid URI (see e.g. http://webmasters.stackexchange.com/questions/73934/how-can-urls-have-a-dot-at-the-end-e-g-www-bla-de). However, it's rather inconvenient, and other markdown parsers (such as GitHub's) do not behave this way - see the rendering of the www.google.com link in this comment, above.
I've had a go at …

Treat trailing full stop after a URL as not being part of the URL

---

src/Markdig.Tests/Specs/GenericAttributesSpecs.md
src/Markdig.Tests/Specs/Specs.cs
src/Markdig/Extensions/GenericAttributes/GenericAttributesParser.cs

The following markdown:
````md
````
output:
````html
<h1 prop1 rop2>Heading</h1>
````
The second attribute `prop2` is not correctly added to the output.

GenericAttributes: The first character of the second boolean attribute is skipped

---

src/Markdig.Tests/Specs/MediaSpecs.md
src/Markdig.Tests/Specs/Specs.cs
src/Markdig/Extensions/MediaLinks/MediaLinkExtension.cs

The following markdown:
````
````
Ouputs:
````html
<p><video width="500" height="281" controls><source type="video/mp4" src="https://sample.com/video.mp4"></source></video></iframe></p>
````
The `</iframe>` is unexpected as there is no opening tag.

MediaLinkExtension: Remove unexpected closing tag

---

src/Markdig/Extensions/Abbreviations/AbbreviationParser.cs

There was an issue with an abbreviation term being at the start of the paragraph, in which the index does not update and therefore words can be repeated. This fixes it!

Fix abbreviation at start of paragraphs

---

src/Markdig.Tests/Specs/AbbreviationSpecs.md
src/Markdig.Tests/Specs/Specs.cs
src/Markdig/Extensions/Abbreviations/AbbreviationParser.cs

There was an issue with abbreviations matching on a section of a word. For example: PR was matching on PRAA.

Fix abbreviation matching

---

src/Markdig/Renderers/Html/CodeBlockRenderer.cs
src/Markdig/Renderers/Html/HeadingRenderer.cs
src/Markdig/Renderers/Html/ListRenderer.cs
src/Markdig/Renderers/Html/ParagraphRenderer.cs
src/Markdig/Renderers/Html/QuoteBlockRenderer.cs
src/Markdig/Renderers/Html/ThematicBreakRenderer.cs
src/Markdig/Renderers/HtmlRenderer.cs

#104 I would really like to see this feature as well. From my understanding of your comments, these changes are what is necessary to enable it. Please accept this contribution to enable the feature or let me know what else needs to get done to enable it.
Thanks for creating such a great/useful library!!!

Added EnableHtmlForBlock flag on HtmlRenderer for issue #104

---

src/Markdig.Tests/Markdig.Tests.csproj
src/Markdig.Tests/TestPlainText.cs
src/Markdig/Markdown.cs

Follow up of work on #140 that gives users easy interface to strip markdown without adding any HTML.
Fixes #104 even more

Add simple helper that enables conversion to plain text

---

src/Markdig.Tests/TestNormalize.cs
src/Markdig/Extensions/AutoLinks/AutoLinkExtension.cs
src/Markdig/Extensions/AutoLinks/AutoLinkParser.cs
src/Markdig/Extensions/AutoLinks/NormalizeAutoLinkRenderer.cs
src/Markdig/Renderers/Normalize/NormalizeOptions.cs
src/Markdig/Syntax/Inlines/LinkInline.cs

Part of #155 
Question here: Are we normalizing auto links to the InlineLink representation OR back to their original form.
If we want to go back to the original form, we need to extend the syntax (IMHO)
I am for normalizing to InlineLinks.

Add Normalization Support for AutoLinks

---

src/Markdig/Extensions/MediaLinks/MediaOptions.cs

I presume MP3 wasn't intentionally left out this list?

Media link extension to support MP3 by default

---

src/Markdig.Tests/Specs/MediaSpecs.md
src/Markdig.Tests/Specs/Specs.cs
src/Markdig/Extensions/MediaLinks/MediaLinkExtension.cs

fixes #187 
* refactored MediaLinkExtensions to make it pluggable
* add support for yandex.music (audio)
* add support for ok.ru (video)
* failed to add support for vk.ru (need to supply hash that could not be guessed from URI)
* failed to add support for soundcloud (same reason)

Added yandex.music & ok.ru support to MediaLinkExtension

---

src/Markdig.Tests/Specs/Specs.cs
src/Markdig.Tests/Specs/Specs.tt

I'm using VS2017 test runner to run unit tests from this solution, and it has names like "Example0??". It's really confusing.
I fixed names to explicitly include name of spec file, so it starts looking like this (see s/shot)

Improve discoverability of test in VS test runner

---

src/Markdig.Tests/Markdig.Tests.csproj
src/Markdig.Tests/TestRelativeUrlReplacement.cs
src/Markdig/Renderers/HtmlRenderer.cs

HTML renderer supports converting relative URLs on links and images to absolute #143
Doesn't touch links inside HTML blocks, just markdown defined blocks
Added a few basic unit tests.

Convert relative URLs to absolute

---

src/Markdig.Tests/project.json

to address Resharper test runner problems
The problems with running test in R# is solved by upgrading NUnit3TestAdapter  to latest version.
This is per R# support recommendation and solves issue for me

Upgrade NUnit3TestAdapter from 3.2 to 3.9 

---

src/Markdig/MarkdownExtensions.cs

This PR adds an overload of the `MarkdownPipelineBuilder.Use<T>` method that receives an instance of an `IMarkdownExtension`, for the cases where the extension has a constructor requiring parameters and cannot be instantiated by the existing `Use<T>` method.
Syntax looks like:
```csharp
var pipeline = new MarkdownPipelineBuilder()
.Use(new MyAwesomeExtension("param1", "param2")) // <== this
.UseAdvancedExtensions()
.Build();
```

Add alternative `Use` extension method to `MarkdownPipelineBuilder` that receives an object instance

---

src/Markdig/Extensions/TextRenderer/ConfigureNewLineExtension.cs
src/Markdig/MarkdownExtensions.cs

This PR adds an extension which allows devs to define what string to use for line-endings when writing.
As per my comment in #211, [`Markdig` always uses `\n` for line-breaks](https://github.com/lunet-io/markdig/blob/master/src/Markdig/Renderers/TextRendererBase.cs#L32). This extension exposes an easy way to override the default behavior when defining the pipeline.
Below is an example on how to define that line-endings should use `Environment.NewLine`:
```csharp
var pipeline = new MarkdownPipelineBuilder()
.ConfigureNewLine(Environment.NewLine)
.UseAdvancedExtensions()
.Build();
```
---
ps: This PR builds on #213, which should be merged first.

Add `ConfigureNewLineExtension` markdown extension

---

src/Markdig.Tests/Markdig.Tests.csproj
src/Markdig.Tests/TestConfigureNewLine.cs

Add unit tests for configuring custom line-endings for the generated HTML through `ConfigureNewLineExtension`'s `ConfigureNewLine` introduced in #214

Add tests for `ConfigureNewLineExtension`'s `ConfigureNewLine`

---

src/Markdig/Markdig.csproj

Cross target .NETSTANDARD 2.0 to eliminate dependencies on modern runtimes.

Cross target .NETSTANDARD 2.0

---

src/Markdig/Markdig.csproj

Wicktionary [marks](https://en.wiktionary.org/wiki/powerfull) "powerfull" as an "archaic form of powerful", so I suppose it could be fixed?

Fix spelling in package description

---

src/Markdig/Extensions/AutoIdentifiers/AutoIdentifierExtension.cs

This PR makes AutoIdentifierExtension thread safe when using a single `MarkdownPipeline` in multiple threads.
https://github.com/dotnet/docfx/issues/2972

Make AutoIdentifierExtension thread safe

---

src/Markdig/Parsers/MarkdownParser.cs
src/Markdig/Syntax/MarkdownDocument.cs

I think this would be a nice feature to have (I know I need it).
I've tried to do it by using a block parser just to count lines, but, while it worked, it seemed overkill considering the value is already known, just hidden.
```csharp
private class LineCounter : BlockParser
{
public int Count => _count + 1;
private int _count = -1;
public override BlockState TryOpen(BlockProcessor processor)
{
_count = processor.LineIndex;
return BlockState.None;
}
}
```

Expose the number of lines in a document

---

src/Markdig.Tests/TestSourcePosition.cs
src/Markdig/Extensions/Footnotes/FootnoteParser.cs
src/Markdig/MarkdownPipelineBuilder.cs
src/Markdig/Parsers/ParagraphBlockParser.cs
src/Markdig/Syntax/LinkReferenceDefinitionGroup.cs
src/Markdig/Syntax/SourceSpan.cs

This does not affect HTML rendering at all, it merely exposes more information to the syntax tree:
- Keep all LinkReferenceDefinitions (doesn't overwrite same-named ones)
- Sets the correct lines and spans for them
- Sets the content and source locations for FootnoteLinkReferenceDefinitions

Fix Link and Footnote reference definitions in syntax tree

---

changelog.md
src/Markdig/Parsers/BlockProcessor.cs
src/Markdig/Parsers/MarkdownParser.cs
src/Markdig/Syntax/MarkdownDocument.cs

This makes precise source locations much more reliable since it removes the need to ferry around two line and column numbers alongside the span. Sample location algorithm made possible by this:
https://github.com/MihaZupan/MarkdownValidator/blob/master/src/MarkdownValidator/Warnings/WarningLocation.cs#L54-L73
I think it being available only when PreciseSourceLocation is set is fitting.

 Expose line start indexes

---

src/Markdig.Tests/TestImageAltText.cs
src/Markdig/Parsers/Inlines/LinkInlineParser.cs

#251 
All tests are passing so I don't think it breaks anything else?

Empty image alt text for link reference definitions

---

src/Markdig.Tests/Specs/AutoLinks.md
src/Markdig/Helpers/LinkHelper.cs

Addresses #258 
The issue with the Specs file remains, do you want me to commit it anyway?

Allow #, ? and : instead of only / as the domain separator for AutoLinks

---

src/Markdig/Extensions/AutoLinks/AutoLinkExtension.cs
src/Markdig/Extensions/AutoLinks/AutoLinkParser.cs
src/Markdig/Helpers/OrderedList.cs
src/Markdig/MarkdownExtensions.cs

Make AutoLink ValidPreviousCharacters configurable

---

src/Markdig.Tests/TestConfigureNewLine.cs
src/Markdig.Tests/TestPlainText.cs
src/Markdig/Renderers/Html/CodeBlockRenderer.cs
src/Markdig/Renderers/Html/HeadingRenderer.cs
src/Markdig/Renderers/Html/Inlines/LineBreakInlineRenderer.cs
src/Markdig/Renderers/Html/ListRenderer.cs
src/Markdig/Renderers/Html/ParagraphRenderer.cs
src/Markdig/Renderers/Html/QuoteBlockRenderer.cs

PR updates the following renderers to ensure a new line:
- CodeBlockRenderer
- HeadingRenderer
- LineBreakInlineRenderer
- ListRenderer
- ParagraphRenderer
- QuoteBlockRenderer
Please let me know if you have any comments or amends.

fixes #196 ensuring line breaks when renderer does not have html enabled

---

src/Markdig/Extensions/AutoIdentifiers/AutoIdentifierOptions.cs

Clarified 'None' option in the options for the auto-identifiers extension. Fixes #266 .

AutoIdentifierOptions clarification

---

src/Markdig/Markdown.cs
src/Markdig/MarkdownParserContext.cs
src/Markdig/Parsers/BlockProcessor.cs
src/Markdig/Parsers/InlineProcessor.cs
src/Markdig/Parsers/MarkdownParser.cs

Adds markdown parser context

---

src/Markdig/Markdig.csproj

Chose the license expression based on what GitHub Detects.
A project I work on generates our Third Party notices files using ClearlyDefined.io and they are having trouble finding you license.  They said this would fix that.  This assumes you package based on the csproj not a nuspec that I couldn't find.

Add the license expression to the `csproj`

---

src/Markdig/Extensions/Tables/HtmlTableRenderer.cs

This request adds the ability to write `TableRow` attributes (attributes can be added to rows when accessing the document after parsing).  
I won't take it bad if you're not interested 😄

HtmlTableRenderer: writing <tr> attributes

---

src/Markdig/Extensions/Emoji/EmojiParser.cs

We meet a performance issue when we need to use multiple pipeline. After checking the profiling file and have some local test, I find EmojiParser.Initialize is the problem. At the meantime, we don't need to build the PrefixTree for each instance. 
This PR have no logic change, just move the logic to the static constructor.

fix emoji performance issue when multiple pipeline needed

---

src/Markdig/Extensions/Emoji/EmojiParser.cs
src/Markdig/Helpers/CompactPrefixTree.cs

Drops CompactPrefixTree's allocations to about half. As a result build times are also lower by about 50%.

Improve CompactPrefixTree's memory footprint

---

src/Markdig.Tests/Specs/MathSpecs.cs
src/Markdig.Tests/Specs/MathSpecs.md
src/Markdig.Tests/TestParser.cs
src/Markdig/Extensions/Mathematics/HtmlMathBlockRenderer.cs
src/Markdig/Extensions/Mathematics/HtmlMathInlineRenderer.cs

Added bracketing to math expressions for better rendering support without fixups in various math libraries. 
- bracket  `\(` and `\)`  for inline expressions
- bracket `\[` and `\]` for block expressions
References Issue #307
For reference with other parsers (primarily PanDoc):
[BabelMark Specs](https://johnmacfarlane.net/babelmark2/?text=Math+expressions%0A%0A%24%5Cfrac%7Bn!%7D%7Bk!(n-k)!%7D+%3D+%5Cbinom%7Bn%7D%7Bk%7D%24%0A%0A%24%24%5Cfrac%7Bn!%7D%7Bk!(n-k)!%7D+%3D+%5Cbinom%7Bn%7D%7Bk%7D%24%24%0A%0A%24%24%0A%5Cfrac%7Bn!%7D%7Bk!(n-k)!%7D+%3D+%5Cbinom%7Bn%7D%7Bk%7D%0A%24%24%0A)

Add Bracketing around Math Expressions for improved MathLib Rendering

---

src/Markdig.Tests/TestPlainText.cs
src/Markdig/Renderers/Html/Inlines/HtmlEntityInlineRenderer.cs
src/Markdig/Renderers/Html/Inlines/LiteralInlineRenderer.cs

The `ToPlainText` should not resulted in html entities.
Current version:
```cs
> Markdig.Markdown.ToPlainText("foo<bar")
"foo&lt;bar\n"
> Markdig.Markdown.ToPlainText("foo&lt;bar")
"foo&lt;bar\n"
```
Expacted:
```cs
> Markdig.Markdown.ToPlainText("foo<bar")
"foo<bar\n"
> Markdig.Markdown.ToPlainText("foo&lt;bar")
"foo<bar\n"
```

Fix ToPlainText with htmlentity

---

.gitignore
changelog.md
src/Markdig.Tests/MiscTests.cs
src/Markdig/Markdown.cs
src/Markdig/Renderers/Html/Inlines/HtmlEntityInlineRenderer.cs
src/Markdig/Renderers/Html/Inlines/LiteralInlineRenderer.cs

`EnableHtmlEscape` should have been used instead of `EnableHtmlForInline`.
Caught by a test from docfx.

Fix regression from #315

---

src/Markdig.Tests/MiscTests.cs
src/Markdig/Helpers/LinkHelper.cs

Fixes #356 
The cause for the last character disappearing stems from [this span calculation](https://github.com/lunet-io/markdig/blob/master/src/Markdig/Extensions/AutoLinks/AutoLinkParser.cs#L170) that uses `link.Length` even though backticks could be removed from the string.
This honors the difference between links and autolinks as stated [in CommonMark](https://spec.commonmark.org/0.29/#example-306) and does not allow backtick escaping in automatic autolinks.

Ignore backticks in GFM AutoLinks

---

changelog.md
src/Markdig.Tests/MiscTests.cs
src/Markdig/Parsers/Inlines/LinkInlineParser.cs
src/Markdig/Syntax/Inlines/Inline.cs

Fixes #371 
Actual change is just f16ee82
I am not 100% that this doesn't cause any regressions, I tried to test as many cases as I could come up with. @yishengjin1413 do you have an example that this wouldn't work on?

Balanced link brackets

---

appveyor.yml
changelog.md
src/Markdig.Tests/TestStringSliceList.cs
src/Markdig/Extensions/AutoIdentifiers/AutoIdentifierExtension.cs
src/Markdig/Extensions/AutoLinks/AutoLinkParser.cs
src/Markdig/Extensions/SmartyPants/SmartyPantsInlineParser.cs
src/Markdig/Extensions/Tables/GridTableParser.cs
src/Markdig/Extensions/Tables/GridTableState.cs
src/Markdig/Helpers/CharHelper.cs
src/Markdig/Helpers/CompactPrefixTree.cs
src/Markdig/Helpers/CustomArrayPool.cs
src/Markdig/Helpers/HtmlHelper.cs
src/Markdig/Helpers/StringBuilderExtensions.cs
src/Markdig/Helpers/StringLine.cs
src/Markdig/Helpers/StringLineGroup.cs
src/Markdig/Helpers/StringSlice.cs
src/Markdig/Markdig.targets
src/Markdig/Markdown.cs
src/Markdig/MarkdownPipeline.cs
src/Markdig/Parsers/BlockProcessor.cs
src/Markdig/Parsers/FencedBlockParserBase.cs
src/Markdig/Parsers/HtmlBlockParser.cs
src/Markdig/Parsers/InlineProcessor.cs
src/Markdig/Parsers/Inlines/LinkInlineParser.cs
src/Markdig/Parsers/MarkdownParser.cs
src/Markdig/Renderers/TextRendererBase.cs
src/Markdig/Syntax/ContainerBlock.cs
src/Markdig/Syntax/LeafBlock.cs

A bunch of random optimizations.
Most interesting (and responsible for perf) ones to look at are:
253be5c afe4308 aefad21
I was mainly playing whack-a-mole with memory allocations, time improvement comes mainly from 253be5c.

10% time and 50% memory improvement

---

src/Markdig.Tests/TestDescendantsOrder.cs
src/Markdig.Tests/TestParser.cs
src/Markdig.Tests/TestPlayParser.cs
src/Markdig.Tests/TestSourcePosition.cs
src/Markdig/Extensions/Bootstrap/BootstrapExtension.cs
src/Markdig/Extensions/Globalization/GlobalizationExtension.cs
src/Markdig/Helpers/CharHelper.cs
src/Markdig/Syntax/Inlines/ContainerInline.cs
src/Markdig/Syntax/MarkdownObjectExtensions.cs

We were missing a few conveniance overloads (#63)
```c#
IEnumerable<T> Descendants<T>(this MarkdownObject) where T : Inline
IEnumerable<T> Descendants<T>(this MarkdownObject) where T : Block
```
Since these can't coexist in C#, I added one `where T : MarkdownObject` that then calls the appropriate internal overload for optimal traversal (has the added bonus of not allocating when it's obvious there can't be any descendants).
Added tests for all the different overloads to make sure the traversal logic is correct.

Add missing Descendants<T> api

---

readme.md

Both the Bootstrap and YAML frontmatter aren't included in `UseAdvancedExtensions`, but the readme didn't specify that.

Add Bootstrap and YAML to exclusion list in readme

---

src/Markdig.Tests/TestLineReader.cs
src/Markdig/Helpers/LineReader.cs
src/Markdig/Parsers/MarkdownParser.cs

Closes #388
Discussion for reference: https://github.com/lunet-io/markdig/pull/388#issuecomment-580429867

Optimize LineReader.ReadLine

---

src/Markdig/Helpers/CharacterMap.cs

The `CharacterMap<T>` constructor counts the occurrence of each opening character, but doesn't use the actual count.
This PR replaces the `Dictionary<char, int>` by a `HashSet<char>`. The dictionary used to be indexed three or four times per iteration though the loop, the hashSet is indexed once per iteration.

Use HashSet<T> instead of Dictionary<TKey, TValue> in CharacterMap<T>

---

src/Markdig/Helpers/CharacterMap.cs

`CharacterMap<T>` uses a `bool[] isOpeningCharacter` for quick lookup.
This PR replaces that by a custom `BitVector128` that stores 128 bits is two ulong fields using a fixed size buffer.
This results in a measurable speedup:
The benchmark:
public class Program
{
private string text = File.ReadAllText("spec.md");
[Benchmark]
public void TestMarkdig()
{
Markdown.Parse(text);
}
private static void Main()
{
BenchmarkRunner.Run<Program>();
}
}
The results on .NET Framework:
BenchmarkDotNet=v0.10.6, OS=Windows 10.0.18363
Processor=Intel Core i7-7700 CPU 3.60GHz (Kaby Lake), ProcessorCount=8
Frequency=10000000 Hz, Resolution=100.0000 ns, Timer=UNKNOWN
[Host]     : Clr 4.0.30319.42000, 64bit RyuJIT-v4.8.4075.0
DefaultJob : Clr 4.0.30319.42000, 64bit RyuJIT-v4.8.4075.0
Before:
|      Method | …

Use BitVector128 in CharacterMap<T>

---

src/Markdig/Helpers/StringLineGroup.cs

This PR contributes a few improvements to `StringLineGroup`.
A memory leak was fixed and code duplication reduced.
First, the case where `Count == 1` has been moved before the case where `Count == 0`, simply because it is so much more common. Indeed, out of 1023 unit tests that call this method, 872 execute the `Count == 1` branch, but none of them execute the `Count == 0` branch.
Secondly, the loop was restructured to simplify it and reduce code duplication. Using `ref var line = ref Lines[i];`, the `Lines` array is indexed only once per iteration.
`_offset++;` has been moved into the `if` branch, so that the `_offset--;` in the else branch can be removed.

Some optimizations in StringLineGroup

---

src/Markdig/Renderers/Html/HeadingRenderer.cs

The rendered HTML for Heading level 7 and above was incorrect.
This PR fixes that.
In addition, a minor optimization removes the range check over the array bounds.

Fixed a bug in HeadingRenderer

---

src/Markdig.Tests/Specs/GridTableSpecs.md
src/Markdig.Tests/TestPlayParser.cs
src/Markdig/Extensions/Tables/HtmlTableRenderer.cs

Allow the output of HtmlTableRenderer to be processed by XML processor.

Make output of HtmlTableRenderer XML wellformed

---

src/Markdig/Renderers/RendererBase.cs

This PR contains a few small optimizations in `RendererBase`.
It uses some recent C# features, such as pattern matching, to make the code more readable.
It does not changes the semantics of the code. In fact, I believe that the `Write(MarkdownObject obj)` method contains abug, and this PR does not attempt to fix it.
To understand why there may be a bug here, consider this block of code:
if (!renderersPerType.TryGetValue(objectType, out renderer))
{
for (int i = 0; i < ObjectRenderers.Count; i++)
{
var testRenderer = ObjectRenderers[i];
if (testRenderer.Accept(this, obj))
{
renderersPerType[objectType] = renderer = testRenderer;
break;
}
}
}
Notice how renderersPerType caches renderers based on the type of the MarkdownObject, whereas the `IMarkdownObjectRenderer.Accept(RendererBase …

Optimized RendererBase

---

src/Markdig/Markdig.targets

make dotnet framework ReferenceAssemblies Private,
the dotnet framework ReferenceAssemblies are used for build on none-windows platform, should not be used as external dependencies

make dotnet framework ReferenceAssemblies Private

---

src/Markdig/Parsers/ListBlockParser.cs

While the primary purpose of these changes is to improve the readability of the code, they may have a small positive effect on performance as well.

Cleanup ListBlockParser

---

src/Markdig.Tests/Specs/MediaSpecs.generated.cs
src/Markdig.Tests/Specs/MediaSpecs.md
src/Markdig.Tests/TestMediaLinks.cs
src/Markdig/Extensions/MediaLinks/MediaLinkExtension.cs

I noticed this when using both the Bootstrap extension and the Media Links extension. When Bootstraps adds `img-fluid`, the Media Link extension didn't add their classes as well. This PR should fix that.

Fix media link classes not being added

---

src/Markdig.Tests/Specs/AutoLinks.generated.cs
src/Markdig.Tests/Specs/AutoLinks.md
src/Markdig/Extensions/AutoLinks/AutoLinkParser.cs

This fixes [437](https://github.com/lunet-io/markdig/issues/437)
Extends autolink functionality to be able to deal with tel:+1234567890.
Includes test.

Autolink tel: uri

---

src/Markdig.Tests/Specs/PipeTableGfmSpecs.generated.cs
src/Markdig.Tests/Specs/PipeTableGfmSpecs.md
src/Markdig.Tests/Specs/PipeTableSpecs.generated.cs
src/Markdig.Tests/Specs/PipeTableSpecs.md
src/Markdig/Extensions/Tables/PipeTableOptions.cs
src/Markdig/Extensions/Tables/PipeTableParser.cs
src/Markdig/Extensions/Tables/Table.cs
src/Markdig/MarkdownExtensions.cs
src/SpecFileGen/Program.cs

This is a potential fix for #454.
In this PR I'm introducing `PipeTableOptions.UseHeaderForColumnCount`, an option that allows switching the PipeTables extension's normalization behavior. It's defaulting to the current behavior (find the row with the most columns and make sure all other rows have the same amount of cells). When setting this option to `true`, the normalization will follow the [example in GitHub's spec](https://github.github.com/gfm/#example-202) and remove/add cells in all rows until they match the number of cells in the header row.
I'm adding this as a draft PR for now since I need some guidance around the test suite:
Right now, I've changed the markdown example specs to conform to the new behavior and made the new behavior the default. Ideally, we'd have tests for both, …

Pipe Tables: Normalize using header column count

---

src/Markdig.Tests/TestReferralLinks.cs
src/Markdig/Extensions/NoRefLinks/NoFollowLinksExtension.cs
src/Markdig/Extensions/ReferralLinks/ReferralLinksExtension.cs
src/Markdig/MarkdownExtensions.cs
src/Markdig/Renderers/Html/Inlines/AutolinkInlineRenderer.cs
src/Markdig/Renderers/Html/Inlines/LinkInlineRenderer.cs

This fixes #456 .
It allows writing custom rel into links. More tests are added.
I think there are two things that needs to be confirmed.
1. I consider that the name `RelXXX` is much suitable than `ReferralXXX` mentioned in #456 . For example, `UseRelLinks` has a straightfoward meaning to set rel property in links. If so, I will make another change.
2. Considering compatibility, I didn't remove the parts related to "nofollow" rel in links. Instead, I marked the parts as obsolete, such as `NoFollowLinksExtension`. I don't know whether it is an acceptable way.

Write custom rel into links 

---

src/Markdig.Tests/Markdig.Tests.csproj
src/Markdig.Tests/TestDescendantsOrder.cs
src/Markdig/Helpers/ArrayHelper.cs
src/Markdig/Markdig.targets
src/Markdig/Syntax/ContainerBlock.cs
src/Markdig/Syntax/Inlines/ContainerInline.cs
src/Markdig/Syntax/MarkdownObjectExtensions.cs

I am the author of [Markdig.Wpf](https://github.com/Kryptos-FR/markdig.wpf) and recently support for .NET framework was dropped in Markdig (https://github.com/lunet-io/markdig/pull/416). That is a huge breaking change for me since it means my library cannot be used anymore in traditional WPF appplication (i.e. not using netcore3.1 or later).
I propose to bring back at least net45 support since it doesn't need to many changes (only `Array.Empty<T>` need special care as of now).
I was also supporting net40 but it seems that it is already a done deal here. It was requested by the Visual Studio setup team since they are using my library (https://github.com/Kryptos-FR/markdig.wpf/issues/25). I have opened a discussion on my own repo to decide what to do for that net40 support …

Bring back net45 target

---

src/Markdig.Tests/TestContainerInlines.cs
src/Markdig/Syntax/Inlines/ContainerInline.cs
src/Markdig/Syntax/LeafBlock.cs

Add ParentBlock property to ContainerInline

---

.github/workflows/ci.yml

Remove `with` uses latest dotnet, which is now `3.1.402`
Fixes [this](https://github.com/lunet-io/markdig/pull/478/checks?check_run_id=1186626201#step:4:29) build error:
```
Error: C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(127,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.1.  Either target .NET Core 3.0 or lower, or use a version of the .NET SDK that supports .NET Core 3.1.
```

Fix NETSDK1045 CI build failure

---

.github/workflows/ci.yml
src/Markdig/Syntax/Inlines/Inline.cs

`Inline.FirstParentOfType()` is protected. It is handy (for extensions) to have the method outside of the `Markdig.Syntax.Inlines` namespace.

Make Inline.FirstParentOfType public

---

src/Markdig.Tests/TestEmphasisExtended.cs
src/Markdig/Helpers/CharHelper.cs

Fix issue #469 . `&` can be a punctuation in function `CheckUnicodeCategory` of `CharHelper`. If `&` is a  beginner of a html entity or print unicode, it would be parsed by `HtmlEntityParser`.

Fix issue 469

---

src/Markdig.Tests/MiscTests.cs
src/Markdig/Helpers/ThrowHelper.cs
src/Markdig/Markdig.targets
src/Markdig/Parsers/InlineProcessor.cs
src/Markdig/Parsers/MarkdownParser.cs
src/Markdig/Renderers/RendererBase.cs
src/Markdig/Renderers/TextRendererBase.cs
src/Markdig/Syntax/Block.cs

Fixes #497 
Due to the recursive approach to rendering, a very deep AST would trigger a StackOverflow during rendering.
This PR adds a general depth limit used in the rendering phase to detect deep nesting (currently 128 which can't affect any non-malicious inputs).
This shouldn't be problematic at all, offering a cheap fail-fast and StackOverflow protection.
Some inputs hit trivial O(n^2) cases due to depth - `new string('[', 100_000)` or `new string('>', 100_000)`.
It also adds a large depth limit used to fail-fast such inputs that would otherwise take ***minutes*** to process.
The current limit of `10 * 1024` is rather arbitrary - on my machine it means that such inputs will fail after ~200 ms.
For comparison, 8192 results in ~125 ms and 16384 in ~500 ms.
**Note: the problem with this …

Add depth limits to avoid pathological-case parsing times/StackOverflows

---

src/Markdig.Tests/TestPlainText.cs
src/Markdig/Renderers/Html/Inlines/CodeInlineRenderer.cs

Fixes #495 
This PR fixes `CodeInlineRenderer` the same way as [LiteralInlineRenderer](https://github.com/xoofx/markdig/blob/master/src/Markdig/Renderers/Html/Inlines/LiteralInlineRenderer.cs) by checking `EnableHtmlEscape` and call different methods accordingly.

Fix CodeInline to plain text incorrect escape

---

src/Markdig/Renderers/TextRendererBase.cs

Fixes #508 by exposing the [`TextRendererBase.Reset`](https://github.com/xoofx/markdig/blob/3030b72f781f902cb947a173853de95de8924c6c/src/Markdig/Renderers/TextRendererBase.cs#L93-L107) method to the class inheritors.
That change makes it possible to implement custom caches of `HtmlRenderer` instances.

Expose `TextRendererBase.Reset` method to inheritors

---

src/Markdig/Helpers/CharNormalizer.cs
src/Markdig/Helpers/HtmlHelper.cs
src/Markdig/Helpers/LinkHelper.cs
src/Markdig/Helpers/StringLineGroup.cs
src/Markdig/Helpers/ThrowHelper.cs
src/Markdig/Markdown.cs
src/Markdig/MarkdownExtensions.cs
src/Markdig/Polyfills/NullableAttributes.cs

This PR aims to enable nullability for the markdig project. To avoid conflicts with existing PR's, it's proposed that nullability be enabled incrementally on a per-file basis before enabling for the project and removing the directives. This effort is likely to span multiple PRs.

Enable nullability

---

src/Markdig/Markdown.cs

Hello. In my case, I had to add additional classes in html elements. And the best way, in my opinion, was to add attributes on parsed document, and then render this one. And I added this missed method.
Code in my local project:
```
if (inline is LinkInline link)
{
link.GetAttributes()
.AddClass("mud-typography mud-link mud-primary-text mud-link-underline-hover mud-typography-body1");
}
```

ADD: Markdown.ToHtml from MarkdownDocument

---

src/Markdig.Tests/TestReferralLinks.cs
src/Markdig/Extensions/ReferralLinks/ReferralLinksExtension.cs
src/Markdig/MarkdownExtensions.cs
src/Markdig/Renderers/Html/Inlines/AutolinkInlineRenderer.cs

A few nullable changes

---

src/Markdig/Markdown.cs
src/Markdig/Parsers/BlockProcessor.cs
src/Markdig/Parsers/InlineProcessor.cs
src/Markdig/Parsers/MarkdownParser.cs
src/Markdig/Polyfills/NullableAttributes.cs
src/Markdig/Syntax/Block.cs

- `MarkdownParser` is made static (had private ctor before)
- `Block/InlineProcessor` got a set of Setup/Rent/Reset/Release methods
```c#
Markdown.Parse("Hello world!");
```
Before:
After:

Cache the MarkdownParser & Processors

---

src/Markdig.Tests/Specs/JiraLinks.generated.cs
src/Markdig.Tests/Specs/JiraLinks.md
src/Markdig/Extensions/JiraLinks/JiraLinkInlineParser.cs

A digit can also be part of the project key for example T3ST is a valid project key and T3ST-123 is thus a valid Jira issue number but it will not be recognized by this tool. 
I propose to add an OR IsDigit() check like: 'while (current.IsAlphaUpper() || current.IsDigit())'
Thanks for considering to update.

JiraLinkInlineParser.cs - Make digits in JiraKey's posible

---

src/Markdig.Tests/RoundtripSpecs/TestParagraph.cs
src/Markdig.Tests/TestNewLine.cs
src/Markdig/Parsers/Inlines/CodeInlineParser.cs
src/Markdig/Parsers/Inlines/EscapeInlineParser.cs
src/Markdig/Parsers/Inlines/LiteralInlineParser.cs

Fix rendering diff between line endings

---

src/Markdig/Extensions/EmphasisExtras/EmphasisExtraOptions.cs

Correct some small typos in the descriptions of some of the members of EmphasisExtraOptions
I did not find a contributing doc in the repo so I took a look at the recently completed PR and attempted to follow what they were doing.
If you are not accepting contributions, thats ok too.  It won't hurt my feelings 😀.

Fix typo in EmphasisExtraOptions descriptions

---

readme.md

This adds [Markdown.ColorCode](https://github.com/wbaldoumas/markdown-colorcode) as another 3rd party extension option for syntax highlighting to the README.

Add Markdown.ColorCode to README

---

src/Markdig.Tests/TestPlayParser.cs
src/Markdig/Helpers/LinkHelper.cs

Fix LinkReferenceDefinition parse bug when CRLF is used as line ending: https://github.com/dotnet/docfx/issues/7850

Fix link reference definition parse bug with title and CRLF

---

readme.md
src/Markdig.Benchmarks/Markdig.Benchmarks.csproj
src/Markdig/Helpers/CharacterMap.cs
src/Markdig/Markdig.targets
src/Markdig/Polyfills/NullableAttributes.cs

.NETCOREAPP2.1 is no longer supported & .NET6.0 will provide us with with 3 years of support.

Drop .netcoreapp2.1 target and cross target .net6.0

---

src/Markdig/Markdown.cs

Hey,
i know it's not markdigs fault, if the AssemblyFileVersionAttribute is missing on Xamarin.iOS. But I thought it is unfortunate that markdig won't work just because it was not able to get the version string. Besides that missing AssemblyFileVersionAttribute markdig works well on Xamarin.iOS. At least with the markdown documents I tested.
Kind regards

Version "Unknown" if AssemblyFileVersionAttribute is missing

---

src/Markdig/Helpers/LineReader.cs
src/Markdig/Helpers/StringSlice.cs
src/Markdig/Parsers/FencedBlockParserBase.cs
src/Markdig/Parsers/FencedCodeBlockParser.cs
src/Markdig/Parsers/HeadingBlockParser.cs
src/Markdig/Parsers/HtmlBlockParser.cs
src/Markdig/Parsers/IndentedCodeBlockParser.cs
src/Markdig/Parsers/Inlines/CodeInlineParser.cs
src/Markdig/Parsers/Inlines/LinkInlineParser.cs
src/Markdig/Parsers/ListBlockParser.cs
src/Markdig/Parsers/MarkdownParser.cs
src/Markdig/Parsers/ParagraphBlockParser.cs
src/Markdig/Parsers/QuoteBlockParser.cs
src/Markdig/Parsers/ThematicBreakParser.cs
src/Markdig/Roundtrip.md
src/Markdig/Syntax/Block.cs
src/Markdig/Syntax/CodeBlock.cs
src/Markdig/Syntax/FencedCodeBlock.cs
src/Markdig/Syntax/HeadingBlock.cs
src/Markdig/Syntax/IBlock.cs
src/Markdig/Syntax/IFencedBlock.cs
src/Markdig/Syntax/Inlines/CodeInline.cs
src/Markdig/Syntax/Inlines/LinkDelimiterInline.cs
src/Markdig/Syntax/Inlines/LinkInline.cs
src/Markdig/Syntax/LinkReferenceDefinition.cs
src/Markdig/Syntax/ListItemBlock.cs
src/Markdig/Syntax/QuoteBlock.cs

A few changes mainly around reducing the overhead of the `TrackTrivia` impl even when it isn't requested:
- `Span.IndexOfAny('\r', '\n')` in `LineReader`
- Moving all trivia properties to lazy-allocated objects to reduce the size of `Syntax` objects.
- Avoiding work that's only relevant for trivia when it's not needed
I was playing around with two markdown documents for these:
- The Markdig readme
- A random doc [article](https://github.com/microsoft/reverse-proxy/blob/main/docs/docfx/articles/distributed-tracing.md)
Before
|         Method |      Mean |    Error |   StdDev |   Gen 0 |   Gen 1 | Allocated |
|--------------- |----------:|---------:|---------:|--------:|--------:|----------:|
|  MarkdigReadme | 315.18 us | 0.695 us | 1.019 us | 36.1328 | 12.2070 |    169 KB |
| …

Improvements when TrackTrivia is disabled

---

doc/parsing-ast.md
doc/parsing-extensions.md
doc/parsing-overview.md

In reference to #597, here's an initial attempt at starting some prosaic documentation on the workings of the Markdig parser.  I could use some hints as to how the internal guts of the `BlockParser` and `InlineParser` work in order to figure them out enough to document them.  The rest I feel a little more confident in, but that doesn't mean there aren't some glaring mistakes or misunderstandings I made why trying to understand the library from the code.
@xoofx, I'm not sure exactly what your vision was for the overall documentation structure, so I wrote this with the understanding that it would probably be re-structured and re-partitioned into some other organization.  For that reason I tried to keep sections small and atomic enough that they'd still be useful if they have to be shuffled …

Start of documentation on parser

---

src/Markdig/Helpers/CharacterMap.cs

A 1-2.5% improvement for parsing (on x86 LE hardware only for now)
For long runs without an opening character, the vectorized loop is ~8x faster.
| Method | AdvancedPipeline |     Mean |   Error |  StdDev |   Median |
|------- |----------------- |---------:|--------:|--------:|---------:|
|  Parse |            False | 262.6 us | 0.73 us | 3.64 us | 263.5 us |
|  Parse |             True | 366.9 us | 0.43 us | 2.16 us | 367.2 us |
| Method | AdvancedPipeline |     Mean |   Error |  StdDev |
|------- |----------------- |---------:|--------:|--------:|
|  Parse |            False | 259.5 us | 0.18 us | 0.91 us |
|  Parse |             True | 357.9 us | 0.41 us | 2.06 us |

Vectorize CharacterMap.IndexOfOpeningCharacter

---

src/Markdig.Tests/Specs/CommonMark.generated.cs
src/Markdig.Tests/Specs/CommonMark.md
src/Markdig/Parsers/HtmlBlockParser.cs
src/Markdig/Syntax/LinkReferenceDefinitionGroup.cs

Fixes #563
Still an issue with the [Example 539](https://spec.commonmark.org/0.30/#example-539)
```md
[ẞ]
[SS]: /url
```
It seems that compare `OrdinalIgnoreCase` doesn't support Unicode Case folding? Or this particular character: [ẞ Latin Capital Letter Sharp S](https://unicode-table.com/en/1E9E/).
@MihaZupan thoughts?

Update commonmark spec 0.30

---

src/Markdig/Helpers/ObjectCache.cs
src/Markdig/Markdown.cs
src/Markdig/MarkdownPipeline.cs
src/Markdig/Polyfills/ConcurrentQueue.cs

Saves 8 % (~65 ns) on my machine when parsing `Markdown.Parse("foo", _pipeline)` with 
```c#
new MarkdownPipelineBuilder().UsePreciseSourceLocation();
```
and 15 % (~150 ns) with `UseAdvancedExtensions`.

Reduce the overhead of Parse calls

---

src/Markdig.Tests/TestPlainText.cs
src/Markdig/Extensions/Tables/HtmlTableRenderer.cs

This PR adds support for `ToPlainText` for the pipetables extension. Before this, it would simply return all the table html elements, and render plaintext within the table. With this PR, all the table elements are removed from the plaintext output as you would expect as a result of `ToPlainText`

added support for ToPlainText for pipetables extension

---

src/Markdig.Tests/TestYamlFrontMatterExtension.cs
src/Markdig/Extensions/Yaml/YamlFrontMatterExtension.cs

I found a minor flaw in PR #638, which could behave incorrectly in an edge case

More accurate check for YAML renderers

---

src/Markdig/Helpers/HtmlHelper.cs

Eliminate some branches in `HtmlHelper.TryParseHtmlTagOpenTag` (due to `||` comparisons) by using a bitmask approach instead.
Further the generated machine code has a `test jump`-combo, which allows optimizations at cpu-level (macro fusion, etc.).
Other places in that type seem not worthwile, as the count of `cmp`s can't be lowered that the current count is.
The benchmarks are done on a trimmed-down version of the code, to just test these parts of the code changed.
```
|  Method |     Mean |   Error |  StdDev | Ratio | RatioSD | Code Size |
|-------- |---------:|--------:|--------:|------:|--------:|----------:|
| Default | 181.4 ns | 3.48 ns | 3.09 ns |  1.00 |    0.00 |      60 B |
|  Switch | 209.6 ns | 3.65 ns | 3.91 ns |  1.16 |    0.02 |      60 B |
|    Mask | 118.4 ns | 2.40 ns | …
```

Remove some branches in HtmlHelper.TryParseHtmlTagOpenTag by using bitmask

---

src/Markdig.Tests/TestCharHelper.cs
src/Markdig.Tests/TestPipeTable.cs
src/Markdig/Helpers/CharHelper.cs
src/Markdig/Helpers/ThrowHelper.cs
src/Markdig/Parsers/Inlines/EmphasisDescriptor.cs

Align Whitespace and Punctuation definitions with CommonMark

---

src/Markdig.Tests/TestParser.cs
src/Markdig/Parsers/MarkdownParser.cs

Fix ANE when parsing empty documents with trackTrivia enabled

---

contributing.md
readme.md

Adds some simple contributing docs to this library. 😄 
This addresses https://github.com/xoofx/markdig/issues/673.

Add Contributing Docs

---

src/Markdig.Tests/Specs/GridTableSpecs.md

Various small tweaks for syntax consistency, readability, clarity and correctness.

Copyedit the grid table extension documentation

---

src/Markdig/Markdig.targets

This PR drops support for the netcoreapp3.1 target (now out of support).
.netcoreapp3.1 will get the netstandard2.1 target after this update.

Drop netcoreapp3.1 target

---

src/Markdig.Tests/TestSourcePosition.cs
src/Markdig/Parsers/ParagraphBlockParser.cs

Previously, heading's span would be 3-6; where 6 is outside the bounds of the original string.
For the context, the original bug report in Marksman [#156](https://github.com/artempyanykh/marksman/issues/156) (I use markdig there).

Fix incorrect setext heading source span

---

src/Markdig.Tests/TestYamlFrontMatterExtension.cs
src/Markdig/Extensions/Yaml/YamlFrontMatterExtension.cs
src/Markdig/Extensions/Yaml/YamlFrontMatterParser.cs

This PR enables customizing the YAML front matter extension to allow it to appear in the middle of the markdown file.
The [docfx](https://github.com/dotnet/docfx) overwrite file feature leverage this feature to embed multiple YAML fragments in the same markdown file. With this change, docfx can be fully migrated to markdig.
Fixes: https://github.com/dotnet/docfx/issues/8441

Allow YAML front matter in the middle of the document

---

src/Markdig.Tests/TestMediaLinks.cs
src/Markdig/Extensions/MediaLinks/MediaLinkExtension.cs
src/global.json

Allow detect and embed relative URLs for image tag usage of audio and video links. Relates to #715.
Updated linking looks like this:
Note relative links now work picking up media files out of the current folder as well as online links.

Add relative path support for Audio and Video Urls to  MediaLinks Extension

---

src/Markdig/Markdown.cs

Made the markdown class not partial and fixed the ToPlainText summary.

---

src/Markdig/Polyfills/NullableAttributes.cs

- Unity uses a version of "netstandard2.1", but already includes the AllowNull attribute
- This will prevent conflicts with other packages, that might include this attribute as well

Make AllowNull internal to prevent conflicts

---

src/Markdig.Tests/MiscTests.cs
src/Markdig.Tests/TestSourcePosition.cs
src/Markdig/Extensions/Tables/PipeTableParser.cs
src/Markdig/Parsers/InlineProcessor.cs

Update the LeafBlock.Inline source span after `PostProcessInlines` calls.
fixes #731, #730 and #702

Fix source span calculation

---

src/Markdig.Tests/TestEmphasisPlus.cs
src/Markdig/Parsers/Inlines/EmphasisInlineParser.cs
src/Markdig/Syntax/Inlines/EmphasisDelimiterInline.cs

Instead of creating a new StringSlice only containing the delimiter chars, use the provided StringSlice from the match method with an appropriate start and end index.
Marked as draft until it is clear if this change is desired.
Fixes: #735

Better literal delimiter content string slice

---

readme.md

Markdown Editor v2 (Visual Studio 2022)
This is a complete rewrite of the original Markdown Editor with tons of fixes, tweeks, and performance improvements.

Update Visual Studio editor link

---

.github/workflows/ci.yml
src/Markdig.Tests/Markdig.Tests.csproj
src/Markdig.Tests/TestYamlFrontMatterExtension.cs
src/Markdig/Extensions/AutoIdentifiers/AutoIdentifierExtension.cs
src/Markdig/Helpers/BlockWrapper.cs
src/Markdig/Helpers/CharHelper.cs
src/Markdig/Helpers/CharacterMap.cs
src/Markdig/Helpers/FastStringWriter.cs
src/Markdig/Helpers/HexConverter.cs
src/Markdig/Helpers/LineReader.cs
src/Markdig/Helpers/LinkHelper.cs
src/Markdig/Helpers/ObjectCache.cs
src/Markdig/Helpers/StringSlice.cs
src/Markdig/Markdig.targets
src/Markdig/Markdown.cs
src/Markdig/Parsers/Inlines/CodeInlineParser.cs
src/Markdig/Parsers/Inlines/LiteralInlineParser.cs
src/Markdig/Polyfills/Ascii.cs
src/Markdig/Polyfills/EncodingExtensions.cs
src/Markdig/Polyfills/IndexOfHelpers.cs
src/Markdig/Polyfills/SearchValues.cs
src/Markdig/Renderers/HtmlRenderer.cs
src/Markdig/Syntax/Inlines/ContainerInline.cs
src/Markdig/Syntax/Inlines/EmphasisDelimiterInline.cs
src/Markdig/Syntax/Inlines/Inline.cs
src/Markdig/Syntax/MarkdownObject.cs
src/global.json

- Added a .NET 8.0 TFM
- Polyfills for a few new functionalities (`Ascii`, `SearchValues`, `ContainsAnyExcept` ...)
- Replaced the `CharacterMap.IndexOfOpeningCharacter` implementation with a call to `IndexOfAny(SearchValues)`
- Don't need manual vectorization code in Markdig for this anymore
- Also get AVX2 paths and ARM64 acceleration "for free"
- Changed `CodeInlineParser.Match` to make use of vectorized helpers
- Sped up `WriteEscape` & `WriteEscapeUrl` rendering (vectorized scanning via SearchValues)
- A few random alloc / codegen improvements
A few rough numbers from parsing a large markdown document with precise source locations (.NET 8 perf improvements blogpost).
Both `main` and `pr` numbers are from 8.0
| Method         | Job  | Mean       | Error    | Ratio |
|--------------- …

.NET 8.0 and a few other perf improvements

---

src/Markdig/Helpers/EntityHelper.cs
src/Markdig/Helpers/ThrowHelper.cs
src/Markdig/Helpers/UnicodeUtility.cs
src/Markdig/Parsers/FencedBlockParserBase.cs
src/Markdig/Parsers/MarkdownParser.cs
src/Markdig/Polyfills/IndexOfHelpers.cs
src/Markdig/Renderers/RendererBase.cs

- Improves the fenced code block parser a bit
- Avoids a dictionary lookup per object when rendering (using linear scans over small arrays instead)
- Misc
| Method         | Job  | Mean       | Error    | Ratio |
|--------------- |----- |-----------:|---------:|------:|
| Parse          | main | 2,512.1 us | 13.63 us |  1.00 |
| Parse          | pr   | 2,417.2 us | 14.36 us |  0.96 |
|                |      |            |          |       |
| ParseAdvanced  | main | 7,872.1 us | 22.51 us |  1.00 |
| ParseAdvanced  | pr   | 7,906.6 us | 44.54 us |  1.00 |
|                |      |            |          |       |
| Render         | main |   716.3 us |  2.38 us |  1.00 |
| Render         | pr   |   688.6 us |  4.58 us |  0.96 |
|                |      |            |          |       |
| …

A few more perf improvements

---

src/Markdig.Tests/TestStringSliceList.cs
src/Markdig/Helpers/StringLineGroup.cs

Fixes #757, before we return the array enumerator directly, enumerate it will get phantom empty lines.

Make StringLineGroup returns a count limited Enumerator

---

src/Markdig.Tests/TestSourcePosition.cs
src/Markdig/Parsers/InlineProcessor.cs

Fix the source span calculation of the last `LineBreakInline` in paragraph when multiple blocks exists.
I have added the source span calculation for the last `LineBreakInline` in https://github.com/xoofx/markdig/pull/733, but the logic does not handle multiple blocks correctly. This corrects the logic.

Fix source span calculation for LineBreakInline

---

src/Markdig.Tests/TestNormalize.cs
src/Markdig/Renderers/Normalize/CodeBlockRenderer.cs
src/Markdig/Renderers/Normalize/HeadingRenderer.cs
src/Markdig/Renderers/Normalize/Inlines/CodeInlineRenderer.cs
src/Markdig/Renderers/Normalize/Inlines/EmphasisInlineRenderer.cs
src/Markdig/Renderers/Roundtrip/CodeBlockRenderer.cs
src/Markdig/Renderers/Roundtrip/HeadingRenderer.cs
src/Markdig/Renderers/Roundtrip/Inlines/CodeInlineRenderer.cs
src/Markdig/Renderers/Roundtrip/Inlines/EmphasisInlineRenderer.cs
src/Markdig/Renderers/TextRendererBase.cs

This PR introduces an overload on TextRendererBase that writes a character a specific number of times, and utilizes it to eliminate various string allocations.

Eliminate various string allocations

---

src/Markdig.Tests/Specs/MathSpecs.md

Fixing what I assume is a typo in one of the documentation files.

Fixed a typo in MathSpecs.md

---

src/Markdig.Tests/TestSourcePosition.cs
src/Markdig/Extensions/Mathematics/MathInlineParser.cs

Fix math source span calculation.
The span is wrong if a math is followed with more texts:
>  Check("0\n012 \\$abcd\\$ 321", @"
paragraph    ( 0, 0)  0-15
literal      ( 0, 0)  0-0
linebreak    ( 0, 1)  1-1
literal      ( 1, 0)  2-5
**math         ( 1, 4)  6-15** (incorrect)
attributes   ( 0, 0)  0--1
literal      ( 1,10) 12-15
", "mathematics");

Fix math source span

---

src/Markdig/Extensions/Alerts/AlertBlockRenderer.cs
src/Markdig/Extensions/Alerts/AlertInlineParser.cs
src/Markdig/Extensions/Bootstrap/BootstrapExtension.cs

Make alert block headers case-invariant

---

src/Markdig.Tests/TestSourcePosition.cs
src/Markdig/Extensions/Mathematics/MathInlineParser.cs

A follow up fix for #779 . Math span end position should also consider the situation when the math inline is closed with whitespace.

Fix issues for math span calculation

---

src/Markdig.Tests/TestMediaLinks.cs
src/Markdig/Extensions/MediaLinks/HostProviderBuilder.cs

Closes #787
Added support for YouTube Shorts embedding in the media links extension

Support for YouTube Shorts embedding

---

readme.md

Updated broken old GitHub pages link to the new domain https://mermaid.js.org/

Fix mermaid link in readme.md

---

src/Markdig.Tests/TestLinkHelper.cs
src/Markdig/Helpers/LinkHelper.cs

Extra line feeds appear in the parsed link titles containing Windows-style line breaks, because \n that is peeked after \r is not skipped.

Fix extra line feeds in link title

---

src/Markdig/Extensions/Tables/GridTableParser.cs

Instead of the intended index to the table line content, an offset to the global source is used. The resulting offset is beyond the end of the table line, and if there happens to be a bar '|' there, the last character of the line is cut off.
For example:
```
// 01234567 8 9012345 6 7890123
"+--+--+\r\n|11|12\r\n>     |"
```
The start of the second line of the table (9) + the line end (14) is 23, and there is a bar at 23. So this string results in a table containing "11", "1" (not "12").

Fix an incorrect offset in GridTableParser.

---

src/Markdig.Tests/TestSourcePosition.cs
src/Markdig/Extensions/Tables/PipeTableParser.cs

Include opening and closing pipes in the table span

---

src/Markdig.Tests/TestSourcePosition.cs
src/Markdig/Extensions/Abbreviations/AbbreviationParser.cs

The modified end of the previous literal is assigned to the literal next to abbrevion. The test of the abbreviations in TestSourcePosition.cs passes only because there is an abbreviation at the end of the string, and thus no literal remains after it. But add some literals after the abbreviation, say, a period '.', and instead of expected literal with the span 103-103 there will be one with the end less then the start (103-98).

Fix an error in the AbbreviationParser.

---

src/Markdig.Tests/TestLinkHelper.cs
src/Markdig.Tests/TestPlayParser.cs
src/Markdig/Helpers/LinkHelper.cs
src/Markdig/Parsers/Inlines/LinkInlineParser.cs

Here is what I used to fix #830. `LinkHelper.TryParseTitle` is replaced with more structured and clearer one, check it out.

Fix errors in LinkHelper and LinkInlineParser.

---

src/Markdig.Tests/MiscTests.cs
src/Markdig/Extensions/Alerts/AlertInlineParser.cs

Fixes #841.
The second condition is related to the following GitHub Markdown [update note](https://github.com/orgs/community/discussions/16925):
> - Prevent alerts from being nested within other elements.

Check that the alert candidate is not already in an alert block or nested within other elements.

---

src/Markdig.Tests/MiscTests.cs
src/Markdig/Extensions/DefinitionLists/DefinitionListParser.cs

Fixes exception in DefinitionListParser.GetCurrentDefinitionList()

---

src/Markdig.Tests/MiscTests.cs
src/Markdig/Extensions/Tables/GridTableParser.cs

Prevent GridTableParser from looking beyond the end of a line.

---

src/Markdig/Renderers/TextRendererBase.cs

- Added method for clearing all indents
- Added logic in PopIndent for when indents are below 1 (TODO mentioned implementing this)

Implemented better indent control in TextRendererBase

---

src/Markdig.Tests/TestAutoLinks.cs
src/Markdig/Extensions/AutoLinks/AutoLinkOptions.cs
src/Markdig/Extensions/AutoLinks/AutoLinkParser.cs
src/Markdig/Helpers/LinkHelper.cs

Fixes https://github.com/xoofx/markdig/issues/857

Add AutoLinkOptions.AllowDomainWithoutPeriod

---

src/Markdig.Tests/Specs/MathSpecs.md

It is really confusing that `MathInline` is called "math block".

Fix `MathInline` is called "math block"

---

src/Markdig.Tests/TestPipeTable.cs
src/Markdig/Extensions/Tables/GridTableParser.cs
src/Markdig/Extensions/Tables/PipeTableOptions.cs
src/Markdig/Extensions/Tables/PipeTableParser.cs
src/Markdig/Extensions/Tables/TableHelper.cs

Hi
First off, thank you for your great library — I use it to convert Markdown to Open XML in my [DocxTemplater](https://github.com/Amberg/DocxTemplater), and it’s been working beautifully.
In my use case, I needed a way to control column widths in pipe tables. Unfortunately, the grid table syntax wasn't an option because it requires monospaced fonts.
This PR introduces a small but useful enhancement:
- Adds support for inferring column widths in pipe tables based on the number of dashes in the header separator row.
- Activates this behavior via a new option: `PipeTableOptions.InferColumnWidthsFromSeparator`.
- Includes unit tests to ensure the feature works with different table layouts and dash distributions.
This allows authors to write tables like:
```markdown
A | B | C
--|----|--
``` …

Infer pipe table column widths from separator row

---

src/Markdig/Extensions/Alerts/AlertBlock.cs
src/Markdig/Extensions/Alerts/AlertInlineParser.cs
src/Markdig/MarkdownPipeline.cs
src/Markdig/Syntax/MarkdownObject.cs
src/Markdig/Syntax/QuoteBlock.cs

- Do the fast-path check for `!` first since that's likely to fail to lower the overhead on text with lots of regular links.
- Avoid the string allocations for `$"markdown-alert-{alertType.ToString().ToLowerInvariant()}"`
- alertType substring + lowercase + concat result

Improve Alert parsing perf

---

readme.md
src/Markdig.Tests/Specs/AutoLinks.generated.cs
src/Markdig.Tests/Specs/AutoLinks.md
src/Markdig.Tests/Specs/CommonMark.generated.cs
src/Markdig.Tests/Specs/CommonMark.md
src/Markdig.Tests/Specs/EmphasisExtraSpecs.generated.cs
src/Markdig.Tests/Specs/EmphasisExtraSpecs.md
src/Markdig.Tests/TestCharHelper.cs
src/Markdig.Tests/TestHtmlCodeBlocks.cs
src/Markdig/Helpers/CharHelper.cs
src/Markdig/Helpers/HtmlHelper.cs
src/Markdig/Helpers/LinkHelper.cs
src/Markdig/Parsers/HtmlBlockParser.cs

Main changes:
- Definition of "Unicode punctuation character" has changed to also include symbol categories.
- We were using the same helper when parsing autolinks (`<http://...>`) and GFM autolinks (`http://...`)
- The one for AutoLinks seems to have been wrong, updated it to match the spec now
- GitHub appears to allow symbols in its autolinks (e.g. emoji in domain name), so I tried to match that by keeping the old behavior there
- More forms of inline raw HTML comments are allowed: ``
- `search` is apparently an HTML tag now

Update to CommonMark 0.31.2

---

src/Markdig.Tests/TestPlainText.cs
src/Markdig/Renderers/Html/CodeBlockRenderer.cs

I have fixed the bug mentioned in #854.
Please check if my solution works correctly.

Fix bug in `Markdown.ToPlainText` with code blocks

---

src/Markdig.Tests/TestLinkHelper.cs
src/Markdig/Helpers/HtmlHelper.cs
src/Markdig/Helpers/LinkHelper.cs
src/Markdig/Parsers/Inlines/LinkInlineParser.cs

#872 reported an inconsistency between nullable annotation and possible value. In case of no title exists in a link syntax, consumers except `Title` property returns a null string. But current behavior is `Title` returning an empty string, This PR fixes the inconsistency by make `Title` property null if link title is not exist.

Fix #872 by reserve null title string.

---

src/Markdig.Tests/RoundtripSpecs/TestUnorderedList.cs
src/Markdig/Renderers/Roundtrip/ListRenderer.cs

fixes #878 by supporting indent and 0 blocks

Fixes #878: RoundtripRenderer: render indent and 0 blocks for ordered lists

---

src/Markdig.Tests/TestPipeTable.cs
src/Markdig/Extensions/Tables/PipeTableParser.cs

Fixes the following issue where a table will not be rendered if there isn't an extra line before the table. 
https://github.com/xoofx/markdig/issues/818
For example this will not render correctly
```
Here is the table:
| Key   | Value    |
| ----  | -------- |
| Color | Blue     |
| Size  | Medium   |
```
But this will because there's an extra new line before the table starts
```
Here is the table:
| Key   | Value    |
| ----  | -------- |
| Color | Blue     |
| Size  | Medium   |
```
Not handled in this change - whitespace between the new line and the pipe

Add support for a table without an extra new line before it

---

src/Markdig.Tests/TestSourcePosition.cs
src/Markdig/Extensions/Tables/GridTableParser.cs
src/Markdig/Parsers/BlockProcessor.cs

Fixes #881
Adds source position tracking for grid tables and corresponding tests.

Add source position tracking for grid tables

---

src/Markdig.Tests/Specs/GenericAttributesSpecs.generated.cs
src/Markdig.Tests/Specs/GenericAttributesSpecs.md
src/Markdig/Extensions/GenericAttributes/GenericAttributesParser.cs

Remove leading newline in block attributes
