- src/Markdig/Extensions/GenericAttributes/GenericAttributesParser.cs
> fixes issue where using special attributes overwites element id, even when id is not specified

- src/Markdig/MarkdownExtensions.cs
- src/Markdig/MarkdownPipelineBuilder.cs
> Adds fluent extension registration method to MarkdownPipelineBuilder.

- src/Markdig.Tests/Markdig.Tests.csproj
- src/Markdig.Tests/TestOrderedList.cs
- src/Markdig/Helpers/OrderedList.cs
> Add Replace method to replace an element in an OrderedList

- readme.md
- src/Markdig.Benchmarks/Markdig.Benchmarks.nuget.targets
- src/Markdig.Tests/Markdig.Tests.csproj
- src/Markdig.Tests/Specs/JiraLinks.md
- src/Markdig/Extensions/JiraLinks/JiraLink.cs
- src/Markdig/Extensions/JiraLinks/JiraLinkExtension.cs
- src/Markdig/Extensions/JiraLinks/JiraLinkInlineParser.cs
- src/Markdig/Extensions/JiraLinks/JiraLinkOptions.cs
- src/Markdig/Extensions/JiraLinks/JiraLinkRenderer.cs
- src/Markdig/MarkdownExtensions.cs
@xoofx Here's the PR for the JIRA Links extension - thanks for your willingness to include it in the main repository!
> Automatically link JIRA issue references

- src/Markdig.Tests/Specs/Specs.cs
- src/Markdig.Tests/Specs/YamlSpecs.md
- src/Markdig/Extensions/Yaml/YamlFrontMatterBlock.cs
- src/Markdig/Extensions/Yaml/YamlFrontMatterParser.cs
> Implement Pandoc compatible front matter parsing

- src/Markdig.Tests/Specs/EmojiSpecs.md
(Great work btw, thanks a lot!)
> Fix typos in EmojiSpecs.md

- readme.md
- src/Markdig.Tests/Specs/DiagramsSpecs.md
- src/Markdig/Extensions/Diagrams/DiagramExtension.cs
added support for nomnoml diagrams
> Nomnoml support

- src/Markdig.Tests/TestNormalize.cs
- src/Markdig/Extensions/TaskLists/NormalizeTaskListRenderer.cs
- src/Markdig/Extensions/TaskLists/TaskListExtension.cs
> Add Normalization Support for Task Lists

- src/Markdig.Tests/Specs/Specs.cs
- src/Markdig.Tests/Specs/YamlSpecs.md
- src/Markdig/Extensions/Yaml/YamlFrontMatterParser.cs
@xoofx Please see the test case. We got another issue after fix [issue160](https://github.com/lunet-io/markdig/issues/160).
> fix yaml frontmatter issue when ending with a empty line

- src/Markdig.Tests/TestNormalize.cs
- src/Markdig/Extensions/JiraLinks/JiraLinkExtension.cs
- src/Markdig/Extensions/JiraLinks/NormalizeJiraLinksRenderer.cs
> Add Normalization Support for JIRA Links

- src/Markdig.Tests/Specs/AutoLinks.md
- src/Markdig.Tests/Specs/Specs.cs
- src/Markdig.Tests/TestNormalize.cs
- src/Markdig/Extensions/AutoLinks/AutoLinkParser.cs
> AutoLinkParser should to remove mailto: in outputted text

- src/Markdig.Tests/Specs/CustomContainerSpecs.md
> small typo

- src/Markdig.Tests/Markdig.Tests.csproj
- src/Markdig.Tests/TestEmphasisExtraOptions.cs
- src/Markdig/Extensions/EmphasisExtras/EmphasisExtraExtension.cs
- src/Markdig/Parsers/Inlines/EmphasisInlineParser.cs
> Emphasis patch

- readme.md
As you requested in #290.
Please, squash to one commit.
Thx, for this library.
> Add Neo.Markdig.Xaml

- src/Markdig/Extensions/Emoji/EmojiParser.cs
> remove lazy initialize

- src/Markdig.Tests/TestParser.cs
- src/Markdig.Tests/TestPlainText.cs
- src/Markdig/Extensions/CustomContainers/HtmlCustomContainerRenderer.cs
> fix #242: HtmlCustomContainerRenderer does not honour EnableHtmlForBlock == false

- src/Markdig.Tests/Specs/MediaSpecs.generated.cs
- src/Markdig.Tests/Specs/MediaSpecs.md
- src/Markdig/Extensions/MediaLinks/MediaLinkExtension.cs
Fixes lunet-io#335
Also makes sure the URL returned by a provider is escaped.
> Enhancements for YouTube Links

- src/Markdig.Tests/Specs/GenericAttributesSpecs.generated.cs
- src/Markdig.Tests/Specs/GenericAttributesSpecs.md
- src/Markdig.Tests/TestParser.cs
- src/Markdig/Extensions/GenericAttributes/GenericAttributesExtension.cs
- src/Markdig/Extensions/GenericAttributes/GenericAttributesParser.cs
>  Fix GenericAttributes matching of single-char values

- src/Markdig.Tests/Specs/SmartyPantsSpecs.generated.cs
- src/Markdig.Tests/Specs/SmartyPantsSpecs.md
- src/Markdig/Extensions/SmartyPants/HtmlSmartyPantRenderer.cs
- src/Markdig/Extensions/SmartyPants/SmartyPant.cs
- src/Markdig/Extensions/SmartyPants/SmartyPantsExtension.cs
- src/Markdig/Extensions/SmartyPants/SmartyPantsInlineParser.cs
> Fix SmartyPants quote matching

- src/Markdig.Tests/TestContainerBlocks.cs
- src/Markdig.Tests/TestCustomEmojis.cs
- src/Markdig.Tests/TestLinkHelper.cs
- src/Markdig.Tests/TestMarkdigCoreApi.cs
- src/Markdig.Tests/TestParser.cs
- src/Markdig.Tests/TestSmartyPants.cs
- src/Markdig.Tests/TestStringSliceList.cs
- src/Markdig/Extensions/Emoji/EmojiMapping.cs
- src/Markdig/Helpers/CompactPrefixTree.cs
- src/Markdig/Helpers/ExcludeFromCodeCoverageAttribute.cs
- src/Markdig/Helpers/LinkHelper.cs
- src/Markdig/Helpers/StringLineGroup.cs
- src/Markdig/Helpers/ThrowHelper.cs
- src/Markdig/Syntax/ContainerBlock.cs
- src/Markdig/Syntax/SourceSpan.cs
Add some tests and fix a few details that those tests uncovered.
I think I can push coverage to ~98% with reasonable tests like this, the rest would be catching every edge-case handling logic.
> Improve code coverage

- src/Markdig/Parsers/ParagraphBlockParser.cs
While the primary purpose of these changes is to improve the readability of the code, they may have a small positive effect on performance as well.
> Cleanup ParagraphBlockParser

- src/Markdig/Renderers/HtmlRenderer.cs
> Fix relative uri detection to be cross-platform compatible

- src/Markdig/Extensions/Figures/FigureBlockParser.cs
- src/Markdig/Extensions/Mathematics/MathInlineParser.cs
- src/Markdig/Extensions/Tables/TableHelper.cs
- src/Markdig/Extensions/Yaml/YamlFrontMatterParser.cs
- src/Markdig/Helpers/StringSlice.cs
- src/Markdig/Parsers/FencedBlockParserBase.cs
- src/Markdig/Parsers/Inlines/CodeInlineParser.cs
- src/Markdig/Parsers/Inlines/EmphasisInlineParser.cs
- src/Markdig/Parsers/ParagraphBlockParser.cs
This PR is mostly about extracting common logic into a reusable method.
Obviously, care was taken to implement the new method as efficient as possible.
> Added StringSlice.CountAndSkipChar(char)

- src/Markdig.Tests/MiscTests.cs
- src/Markdig/Renderers/HtmlRenderer.cs
Fixes #365 by reusing the url escaping code to also escape the scheme part.
> Escape URLs scheme

- src/Markdig.Tests/MiscTests.cs
- src/Markdig/Renderers/HtmlRenderer.cs
> Fallback to non-punycode encoding for invalid IDN urls

- src/Markdig/Syntax/FencedCodeBlock.cs
- src/Markdig/Syntax/ListItemBlock.cs
> Expose IndentCount of FencedCodeBlock

- src/Markdig.Tests/TestContainerBlocks.cs
- src/Markdig/Syntax/ContainerBlock.cs
> Set Parent in ContainerBlock.set[index] method

- src/Markdig.Tests/Specs/AutoLinks.generated.cs
- src/Markdig.Tests/Specs/AutoLinks.md
- src/Markdig/Extensions/AutoLinks/AutoLinkParser.cs
> Fix tel: treated as autolink

- readme.md
Hello,
I have added a reference to Markdig extensions that renderers various programming languages source code using Prism.js.
> Added a reference to WebStoating.Markdig.Prism

- src/Markdig.Tests/TestPipeTable.cs
- src/Markdig/Extensions/Tables/PipeTableParser.cs
> ignore whitespace at end of pipe table row header

- src/Markdig/Helpers/CompactPrefixTree.cs
- src/Markdig/Helpers/EntityHelper.cs
- src/Markdig/Markdig.targets
- src/Markdig/Polyfills/NullableAttributes.cs
- src/Markdig/Renderers/TextRendererBase.cs
and replace by` NETSTANDARD2_1_OR_GREATER` and `NETCOREAPP3_1_OR_GREATER`
> remove NETCORE constant

- src/Markdig.Tests/Specs/GlobalizationSpecs.generated.cs
- src/Markdig.Tests/Specs/GlobalizationSpecs.md
- src/Markdig/Extensions/Globalization/GlobalizationExtension.cs
> Fix GlobalizationExtension RTL detection

- src/Markdig.Tests/TestContainerBlocks.cs
- src/Markdig/Syntax/ContainerBlock.cs
> Fix typos in ContainerBlock

- src/Markdig/Renderers/RendererBase.cs
> Don't try to use the MT pointer on unsupported platforms

- src/Markdig.Tests/RoundtripSpecs/TestYamlFrontMatterBlock.cs
- src/Markdig.Tests/TestRoundtrip.cs
- src/Markdig/Extensions/Yaml/YamlFrontMatterExtension.cs
- src/Markdig/Extensions/Yaml/YamlFrontMatterHtmlRenderer.cs
- src/Markdig/Extensions/Yaml/YamlFrontMatterRoundtripRenderer.cs
> Add YamlFrontMatterRoundtripRenderer

- src/Markdig/Extensions/MediaLinks/MediaLinkExtension.cs
- src/Markdig/Extensions/MediaLinks/MediaOptions.cs
Relating to issue https://github.com/xoofx/markdig/issues/671
> Option to set controls attribute for MediaLinks

- src/Markdig/Renderers/MarkdownObjectRenderer.cs
Rename a variable in `MarkdownObjectRenderer`
> Rename a variable
